language: python
python:
- '3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
# - '3.8'
before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
- pip install coverage
- pip install pytest-cov

install:
- if [ $TRAVIS_PYTHON_VERSION == 3.8 ]; 
  then pip install -r gklearn/tests/requirements.txt;
  else pip install -r requirements.txt;
  fi
- pip install wheel

script:
- python setup.py bdist_wheel
- pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/

after_success:
- codecov
