language: python

python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'

before_install:
- python --version
- pip install -U pip
- pip install -U pytest
- pip install codecov
- pip install coverage
- pip install pytest-cov

install:
- pip install -r requirements.txt
- pip install wheel

jobs:
  include:
    - python: 3.5
      script:
      - python setup.py bdist_wheel
      - pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/ --ignore=gklearn/tests/test_median_preimage_generator.py
  include:
    - python: 3.6
      script:
      - python setup.py bdist_wheel
      - pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/
  include:
    - python: 3.7
      script:
      - python setup.py bdist_wheel
      - pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/ --ignore=gklearn/tests/test_median_preimage_generator.py
  include:
    - python: 3.8
      script:
      - python setup.py bdist_wheel
      - pytest -v --cov-config=.coveragerc --cov-report term --cov=gklearn gklearn/tests/ --ignore=gklearn/tests/test_median_preimage_generator.py

after_success:
- codecov
